/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ComponenteMantenimiento;

import ComponenteClases.JPanelConFondo;

/**
 *
 * @author Toshib
 */
public class FrmMantenimientoCochera extends javax.swing.JFrame {

    /**
     * Creates new form FrmMantenimientoCochera
     */
    public FrmMantenimientoCochera() {
        initComponents();
        ((JPanelConFondo) panel01).setImagen("/ComponenteImagenes/Disponible.png");
        ((JPanelConFondo) panel02).setImagen("/ComponenteImagenes/Disponible.png");
        ((JPanelConFondo) panel03).setImagen("/ComponenteImagenes/Disponible.png");
        ((JPanelConFondo) panel04).setImagen("/ComponenteImagenes/Disponible.png");
        ((JPanelConFondo) panel05).setImagen("/ComponenteImagenes/Disponible.png");
        ((JPanelConFondo) panel06).setImagen("/ComponenteImagenes/Disponible.png");
        ((JPanelConFondo) panel07).setImagen("/ComponenteImagenes/Disponible.png");
        ((JPanelConFondo) panel08).setImagen("/ComponenteImagenes/Disponible.png");
        ((JPanelConFondo) panel09).setImagen("/ComponenteImagenes/Disponible.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        panel01 = new JPanelConFondo();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LBLEstadoPlaza01 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LBLClientePlaza01 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LBLPlacaPlaza01 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LBLHabitacionPlaza01 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LBLTiempoHPlaza01 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LBLHoraEPlaza01 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LBLHoraSPlaza01 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panel02 = new JPanelConFondo();
        jLabel29 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LBLEstadoPlaza2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LBLClientePlaza2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LBLPlacaPlaza2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LBLHabitacionPlaza2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LBLTiempoHPlaza2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LBLHoraEPlaza2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LBLHoraSPlaza2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        panel03 = new JPanelConFondo();
        jLabel30 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        LBLEstadoPlaza3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LBLClientePlaza3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        LBLPlacaPlaza3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        LBLHabitacionPlaza3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        LBLTiempoHPlaza3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        LBLHoraEPlaza3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        LBLHoraSPlaza3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        panel04 = new JPanelConFondo();
        jLabel31 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        LBLEstadoPlaza4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        LBLClientePlaza4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        LBLPlacaPlaza4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        LBLHabitacionPlaza4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        LBLTiempoHPlaza4 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        LBLHoraEPlaza4 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        LBLHoraSPlaza4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        panel05 = new JPanelConFondo();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        LBLEstadoPlaza5 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        LBLClientePlaza5 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        LBLPlacaPlaza5 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        LBLHabitacionPlaza5 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        LBLTiempoHPlaza5 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        LBLHoraEPlaza5 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        LBLHoraSPlaza5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        panel06 = new JPanelConFondo();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        LBLEstadoPlaza6 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        LBLClientePlaza6 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        LBLPlacaPlaza6 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        LBLHabitacionPlaza6 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        LBLTiempoHPlaza6 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        LBLHoraEPlaza6 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        LBLHoraSPlaza6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        panel07 = new JPanelConFondo();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        LBLEstadoPlaza7 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        LBLClientePlaza7 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        LBLPlacaPlaza7 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        LBLHabitacionPlaza7 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        LBLTiempoHPlaza7 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        LBLHoraEPlaza7 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        LBLHoraSPlaza7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        panel08 = new JPanelConFondo();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        LBLEstadoPlaza8 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        LBLClientePlaza8 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        LBLPlacaPlaza8 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        LBLHabitacionPlaza8 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        LBLTiempoHPlaza8 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        LBLHoraEPlaza8 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        LBLHoraSPlaza8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        panel09 = new JPanelConFondo();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        LBLEstadoPlaza9 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        LBLClientePlaza9 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        LBLPlacaPlaza9 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        LBLHabitacionPlaza9 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        LBLTiempoHPlaza9 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        LBLHoraEPlaza9 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        LBLHoraSPlaza9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(70, 99, 138));

        jPanel1.setBackground(new java.awt.Color(247, 254, 255));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        panel01.setToolTipText("22:00 - 04:00");
        panel01.setPreferredSize(new java.awt.Dimension(48, 48));
        panel01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel01MouseClicked(evt);
            }
        });
        panel01.setLayout(new java.awt.GridBagLayout());

        jLabel28.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        jLabel28.setText("01");
        panel01.add(jLabel28, new java.awt.GridBagConstraints());

        jLabel1.setText("Estado:");

        LBLEstadoPlaza01.setText("Estado");

        jLabel2.setText("Cliente:");

        LBLClientePlaza01.setText("cliente");

        jLabel4.setText("Placa de auto:");

        LBLPlacaPlaza01.setText("Placa de auto");

        jLabel6.setText("Habitacion:");

        LBLHabitacionPlaza01.setText("Habitacion");

        jLabel8.setText("Tiempo de hospedaje:");

        LBLTiempoHPlaza01.setText("tiempo hospedaje");

        jLabel10.setText("Hora de entrada:");

        LBLHoraEPlaza01.setText("Hora de entrada");

        jLabel12.setText("Hora de salida:");

        LBLHoraSPlaza01.setText("Hora de salida");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(panel01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLTiempoHPlaza01, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLEstadoPlaza01, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLPlacaPlaza01, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LBLHabitacionPlaza01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLHoraEPlaza01))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(LBLHoraSPlaza01)))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(LBLClientePlaza01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panel01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LBLEstadoPlaza01))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLClientePlaza01)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LBLPlacaPlaza01))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LBLHabitacionPlaza01))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LBLTiempoHPlaza01))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(LBLHoraEPlaza01))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(LBLHoraSPlaza01))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plaza 01", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        panel02.setToolTipText("22:00 - 04:00");
        panel02.setPreferredSize(new java.awt.Dimension(48, 48));
        panel02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel02MouseClicked(evt);
            }
        });
        panel02.setLayout(new java.awt.GridBagLayout());

        jLabel29.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        jLabel29.setText("02");
        panel02.add(jLabel29, new java.awt.GridBagConstraints());

        jLabel3.setText("Estado:");

        LBLEstadoPlaza2.setText("Estado");

        jLabel5.setText("Cliente:");

        LBLClientePlaza2.setText("cliente");

        jLabel7.setText("Placa de auto:");

        LBLPlacaPlaza2.setText("Placa de auto");

        jLabel9.setText("Habitacion:");

        LBLHabitacionPlaza2.setText("Habitacion");

        jLabel11.setText("Tiempo de hospedaje:");

        LBLTiempoHPlaza2.setText("tiempo hospedaje");

        jLabel13.setText("Hora de entrada:");

        LBLHoraEPlaza2.setText("Hora de entrada");

        jLabel14.setText("Hora de salida:");

        LBLHoraSPlaza2.setText("Hora de salida");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(panel02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLTiempoHPlaza2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLEstadoPlaza2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLPlacaPlaza2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LBLHabitacionPlaza2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLHoraEPlaza2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(LBLHoraSPlaza2)))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(LBLClientePlaza2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panel02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LBLEstadoPlaza2))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLClientePlaza2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LBLPlacaPlaza2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(LBLHabitacionPlaza2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(LBLTiempoHPlaza2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(LBLHoraEPlaza2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(LBLHoraSPlaza2))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plaza 02", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        panel03.setToolTipText("22:00 - 04:00");
        panel03.setPreferredSize(new java.awt.Dimension(48, 48));
        panel03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel03MouseClicked(evt);
            }
        });
        panel03.setLayout(new java.awt.GridBagLayout());

        jLabel30.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        jLabel30.setText("01");
        panel03.add(jLabel30, new java.awt.GridBagConstraints());

        jLabel15.setText("Estado:");

        LBLEstadoPlaza3.setText("Estado");

        jLabel16.setText("Cliente:");

        LBLClientePlaza3.setText("cliente");

        jLabel17.setText("Placa de auto:");

        LBLPlacaPlaza3.setText("Placa de auto");

        jLabel18.setText("Habitacion:");

        LBLHabitacionPlaza3.setText("Habitacion");

        jLabel19.setText("Tiempo de hospedaje:");

        LBLTiempoHPlaza3.setText("tiempo hospedaje");

        jLabel20.setText("Hora de entrada:");

        LBLHoraEPlaza3.setText("Hora de entrada");

        jLabel21.setText("Hora de salida:");

        LBLHoraSPlaza3.setText("Hora de salida");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(panel03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLTiempoHPlaza3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLEstadoPlaza3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLPlacaPlaza3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LBLHabitacionPlaza3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLHoraEPlaza3))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(LBLHoraSPlaza3)))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(LBLClientePlaza3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panel03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(LBLEstadoPlaza3))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLClientePlaza3)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(LBLPlacaPlaza3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(LBLHabitacionPlaza3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(LBLTiempoHPlaza3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(LBLHoraEPlaza3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(LBLHoraSPlaza3))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plaza 03", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        panel04.setToolTipText("22:00 - 04:00");
        panel04.setPreferredSize(new java.awt.Dimension(48, 48));
        panel04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel04MouseClicked(evt);
            }
        });
        panel04.setLayout(new java.awt.GridBagLayout());

        jLabel31.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        jLabel31.setText("04");
        panel04.add(jLabel31, new java.awt.GridBagConstraints());

        jLabel22.setText("Estado:");

        LBLEstadoPlaza4.setText("Estado");

        jLabel23.setText("Cliente:");

        LBLClientePlaza4.setText("cliente");

        jLabel24.setText("Placa de auto:");

        LBLPlacaPlaza4.setText("Placa de auto");

        jLabel25.setText("Habitacion:");

        LBLHabitacionPlaza4.setText("Habitacion");

        jLabel26.setText("Tiempo de hospedaje:");

        LBLTiempoHPlaza4.setText("tiempo hospedaje");

        jLabel27.setText("Hora de entrada:");

        LBLHoraEPlaza4.setText("Hora de entrada");

        jLabel32.setText("Hora de salida:");

        LBLHoraSPlaza4.setText("Hora de salida");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(panel04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLTiempoHPlaza4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLEstadoPlaza4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLPlacaPlaza4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LBLHabitacionPlaza4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLHoraEPlaza4))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(LBLHoraSPlaza4)))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(LBLClientePlaza4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panel04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(LBLEstadoPlaza4))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLClientePlaza4)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(LBLPlacaPlaza4))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(LBLHabitacionPlaza4))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(LBLTiempoHPlaza4))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(LBLHoraEPlaza4))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(LBLHoraSPlaza4))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plaza 04", jPanel6);

        panel05.setToolTipText("22:00 - 04:00");
        panel05.setPreferredSize(new java.awt.Dimension(48, 48));
        panel05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel05MouseClicked(evt);
            }
        });
        panel05.setLayout(new java.awt.GridBagLayout());

        jLabel33.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        jLabel33.setText("05");
        panel05.add(jLabel33, new java.awt.GridBagConstraints());

        jLabel34.setText("Estado:");

        LBLEstadoPlaza5.setText("Estado");

        jLabel35.setText("Cliente:");

        LBLClientePlaza5.setText("cliente");

        jLabel36.setText("Placa de auto:");

        LBLPlacaPlaza5.setText("Placa de auto");

        jLabel37.setText("Habitacion:");

        LBLHabitacionPlaza5.setText("Habitacion");

        jLabel38.setText("Tiempo de hospedaje:");

        LBLTiempoHPlaza5.setText("tiempo hospedaje");

        jLabel39.setText("Hora de entrada:");

        LBLHoraEPlaza5.setText("Hora de entrada");

        jLabel40.setText("Hora de salida:");

        LBLHoraSPlaza5.setText("Hora de salida");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(panel05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLTiempoHPlaza5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel34)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLEstadoPlaza5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel36)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLPlacaPlaza5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel37)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LBLHabitacionPlaza5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLHoraEPlaza5))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(18, 18, 18)
                                .addComponent(LBLHoraSPlaza5)))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(LBLClientePlaza5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panel05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(LBLEstadoPlaza5))
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLClientePlaza5)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(LBLPlacaPlaza5))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(LBLHabitacionPlaza5))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(LBLTiempoHPlaza5))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(LBLHoraEPlaza5))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(LBLHoraSPlaza5))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plaza 05", jPanel7);

        panel06.setToolTipText("22:00 - 04:00");
        panel06.setPreferredSize(new java.awt.Dimension(48, 48));
        panel06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel06MouseClicked(evt);
            }
        });
        panel06.setLayout(new java.awt.GridBagLayout());

        jLabel41.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        jLabel41.setText("06");
        panel06.add(jLabel41, new java.awt.GridBagConstraints());

        jLabel42.setText("Estado:");

        LBLEstadoPlaza6.setText("Estado");

        jLabel43.setText("Cliente:");

        LBLClientePlaza6.setText("cliente");

        jLabel44.setText("Placa de auto:");

        LBLPlacaPlaza6.setText("Placa de auto");

        jLabel45.setText("Habitacion:");

        LBLHabitacionPlaza6.setText("Habitacion");

        jLabel46.setText("Tiempo de hospedaje:");

        LBLTiempoHPlaza6.setText("tiempo hospedaje");

        jLabel47.setText("Hora de entrada:");

        LBLHoraEPlaza6.setText("Hora de entrada");

        jLabel48.setText("Hora de salida:");

        LBLHoraSPlaza6.setText("Hora de salida");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(panel06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLTiempoHPlaza6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel42)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLEstadoPlaza6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel44)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLPlacaPlaza6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel45)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LBLHabitacionPlaza6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLHoraEPlaza6))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel48)
                                .addGap(18, 18, 18)
                                .addComponent(LBLHoraSPlaza6)))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addComponent(LBLClientePlaza6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panel06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(LBLEstadoPlaza6))
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLClientePlaza6)
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(LBLPlacaPlaza6))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(LBLHabitacionPlaza6))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(LBLTiempoHPlaza6))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(LBLHoraEPlaza6))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(LBLHoraSPlaza6))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plaza 06", jPanel8);

        panel07.setToolTipText("22:00 - 04:00");
        panel07.setPreferredSize(new java.awt.Dimension(48, 48));
        panel07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel07MouseClicked(evt);
            }
        });
        panel07.setLayout(new java.awt.GridBagLayout());

        jLabel49.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        jLabel49.setText("07");
        panel07.add(jLabel49, new java.awt.GridBagConstraints());

        jLabel50.setText("Estado:");

        LBLEstadoPlaza7.setText("Estado");

        jLabel51.setText("Cliente:");

        LBLClientePlaza7.setText("cliente");

        jLabel52.setText("Placa de auto:");

        LBLPlacaPlaza7.setText("Placa de auto");

        jLabel53.setText("Habitacion:");

        LBLHabitacionPlaza7.setText("Habitacion");

        jLabel54.setText("Tiempo de hospedaje:");

        LBLTiempoHPlaza7.setText("tiempo hospedaje");

        jLabel55.setText("Hora de entrada:");

        LBLHoraEPlaza7.setText("Hora de entrada");

        jLabel56.setText("Hora de salida:");

        LBLHoraSPlaza7.setText("Hora de salida");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(panel07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLTiempoHPlaza7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel50)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLEstadoPlaza7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel52)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLPlacaPlaza7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel53)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LBLHabitacionPlaza7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLHoraEPlaza7))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel56)
                                .addGap(18, 18, 18)
                                .addComponent(LBLHoraSPlaza7)))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel51)
                .addGap(18, 18, 18)
                .addComponent(LBLClientePlaza7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panel07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(LBLEstadoPlaza7))
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLClientePlaza7)
                    .addComponent(jLabel51))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(LBLPlacaPlaza7))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(LBLHabitacionPlaza7))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(LBLTiempoHPlaza7))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(LBLHoraEPlaza7))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(LBLHoraSPlaza7))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plaza 07", jPanel9);

        panel08.setToolTipText("22:00 - 04:00");
        panel08.setPreferredSize(new java.awt.Dimension(48, 48));
        panel08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel08MouseClicked(evt);
            }
        });
        panel08.setLayout(new java.awt.GridBagLayout());

        jLabel57.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        jLabel57.setText("08");
        panel08.add(jLabel57, new java.awt.GridBagConstraints());

        jLabel58.setText("Estado:");

        LBLEstadoPlaza8.setText("Estado");

        jLabel59.setText("Cliente:");

        LBLClientePlaza8.setText("cliente");

        jLabel60.setText("Placa de auto:");

        LBLPlacaPlaza8.setText("Placa de auto");

        jLabel61.setText("Habitacion:");

        LBLHabitacionPlaza8.setText("Habitacion");

        jLabel62.setText("Tiempo de hospedaje:");

        LBLTiempoHPlaza8.setText("tiempo hospedaje");

        jLabel63.setText("Hora de entrada:");

        LBLHoraEPlaza8.setText("Hora de entrada");

        jLabel64.setText("Hora de salida:");

        LBLHoraSPlaza8.setText("Hora de salida");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(panel08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLTiempoHPlaza8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(jLabel58)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLEstadoPlaza8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(jLabel60)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLPlacaPlaza8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(jLabel61)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LBLHabitacionPlaza8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel63)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLHoraEPlaza8))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel64)
                                .addGap(18, 18, 18)
                                .addComponent(LBLHoraSPlaza8)))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel59)
                .addGap(18, 18, 18)
                .addComponent(LBLClientePlaza8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panel08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(LBLEstadoPlaza8))
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLClientePlaza8)
                    .addComponent(jLabel59))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(LBLPlacaPlaza8))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(LBLHabitacionPlaza8))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(LBLTiempoHPlaza8))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(LBLHoraEPlaza8))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(LBLHoraSPlaza8))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plaza 08", jPanel10);

        panel09.setToolTipText("22:00 - 04:00");
        panel09.setPreferredSize(new java.awt.Dimension(48, 48));
        panel09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel09MouseClicked(evt);
            }
        });
        panel09.setLayout(new java.awt.GridBagLayout());

        jLabel65.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        jLabel65.setText("09");
        panel09.add(jLabel65, new java.awt.GridBagConstraints());

        jLabel66.setText("Estado:");

        LBLEstadoPlaza9.setText("Estado");

        jLabel67.setText("Cliente:");

        LBLClientePlaza9.setText("cliente");

        jLabel68.setText("Placa de auto:");

        LBLPlacaPlaza9.setText("Placa de auto");

        jLabel69.setText("Habitacion:");

        LBLHabitacionPlaza9.setText("Habitacion");

        jLabel70.setText("Tiempo de hospedaje:");

        LBLTiempoHPlaza9.setText("tiempo hospedaje");

        jLabel71.setText("Hora de entrada:");

        LBLHoraEPlaza9.setText("Hora de entrada");

        jLabel72.setText("Hora de salida:");

        LBLHoraSPlaza9.setText("Hora de salida");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(panel09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel70)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLTiempoHPlaza9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addComponent(jLabel66)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLEstadoPlaza9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addComponent(jLabel68)
                                    .addGap(18, 18, 18)
                                    .addComponent(LBLPlacaPlaza9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addComponent(jLabel69)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LBLHabitacionPlaza9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel71)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLHoraEPlaza9))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel72)
                                .addGap(18, 18, 18)
                                .addComponent(LBLHoraSPlaza9)))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel67)
                .addGap(18, 18, 18)
                .addComponent(LBLClientePlaza9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panel09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(LBLEstadoPlaza9))
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLClientePlaza9)
                    .addComponent(jLabel67))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(LBLPlacaPlaza9))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(LBLHabitacionPlaza9))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(LBLTiempoHPlaza9))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(LBLHoraEPlaza9))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(LBLHoraSPlaza9))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plaza 09", jPanel11);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel01MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel01MouseClicked

    private void panel02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel02MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel02MouseClicked

    private void panel03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel03MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel03MouseClicked

    private void panel04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel04MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel04MouseClicked

    private void panel05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel05MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel05MouseClicked

    private void panel06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel06MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel06MouseClicked

    private void panel07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel07MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel07MouseClicked

    private void panel08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel08MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel08MouseClicked

    private void panel09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel09MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel09MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimientoCochera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimientoCochera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimientoCochera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimientoCochera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMantenimientoCochera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLClientePlaza01;
    private javax.swing.JLabel LBLClientePlaza2;
    private javax.swing.JLabel LBLClientePlaza3;
    private javax.swing.JLabel LBLClientePlaza4;
    private javax.swing.JLabel LBLClientePlaza5;
    private javax.swing.JLabel LBLClientePlaza6;
    private javax.swing.JLabel LBLClientePlaza7;
    private javax.swing.JLabel LBLClientePlaza8;
    private javax.swing.JLabel LBLClientePlaza9;
    private javax.swing.JLabel LBLEstadoPlaza01;
    private javax.swing.JLabel LBLEstadoPlaza2;
    private javax.swing.JLabel LBLEstadoPlaza3;
    private javax.swing.JLabel LBLEstadoPlaza4;
    private javax.swing.JLabel LBLEstadoPlaza5;
    private javax.swing.JLabel LBLEstadoPlaza6;
    private javax.swing.JLabel LBLEstadoPlaza7;
    private javax.swing.JLabel LBLEstadoPlaza8;
    private javax.swing.JLabel LBLEstadoPlaza9;
    private javax.swing.JLabel LBLHabitacionPlaza01;
    private javax.swing.JLabel LBLHabitacionPlaza2;
    private javax.swing.JLabel LBLHabitacionPlaza3;
    private javax.swing.JLabel LBLHabitacionPlaza4;
    private javax.swing.JLabel LBLHabitacionPlaza5;
    private javax.swing.JLabel LBLHabitacionPlaza6;
    private javax.swing.JLabel LBLHabitacionPlaza7;
    private javax.swing.JLabel LBLHabitacionPlaza8;
    private javax.swing.JLabel LBLHabitacionPlaza9;
    private javax.swing.JLabel LBLHoraEPlaza01;
    private javax.swing.JLabel LBLHoraEPlaza2;
    private javax.swing.JLabel LBLHoraEPlaza3;
    private javax.swing.JLabel LBLHoraEPlaza4;
    private javax.swing.JLabel LBLHoraEPlaza5;
    private javax.swing.JLabel LBLHoraEPlaza6;
    private javax.swing.JLabel LBLHoraEPlaza7;
    private javax.swing.JLabel LBLHoraEPlaza8;
    private javax.swing.JLabel LBLHoraEPlaza9;
    private javax.swing.JLabel LBLHoraSPlaza01;
    private javax.swing.JLabel LBLHoraSPlaza2;
    private javax.swing.JLabel LBLHoraSPlaza3;
    private javax.swing.JLabel LBLHoraSPlaza4;
    private javax.swing.JLabel LBLHoraSPlaza5;
    private javax.swing.JLabel LBLHoraSPlaza6;
    private javax.swing.JLabel LBLHoraSPlaza7;
    private javax.swing.JLabel LBLHoraSPlaza8;
    private javax.swing.JLabel LBLHoraSPlaza9;
    private javax.swing.JLabel LBLPlacaPlaza01;
    private javax.swing.JLabel LBLPlacaPlaza2;
    private javax.swing.JLabel LBLPlacaPlaza3;
    private javax.swing.JLabel LBLPlacaPlaza4;
    private javax.swing.JLabel LBLPlacaPlaza5;
    private javax.swing.JLabel LBLPlacaPlaza6;
    private javax.swing.JLabel LBLPlacaPlaza7;
    private javax.swing.JLabel LBLPlacaPlaza8;
    private javax.swing.JLabel LBLPlacaPlaza9;
    private javax.swing.JLabel LBLTiempoHPlaza01;
    private javax.swing.JLabel LBLTiempoHPlaza2;
    private javax.swing.JLabel LBLTiempoHPlaza3;
    private javax.swing.JLabel LBLTiempoHPlaza4;
    private javax.swing.JLabel LBLTiempoHPlaza5;
    private javax.swing.JLabel LBLTiempoHPlaza6;
    private javax.swing.JLabel LBLTiempoHPlaza7;
    private javax.swing.JLabel LBLTiempoHPlaza8;
    private javax.swing.JLabel LBLTiempoHPlaza9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panel01;
    private javax.swing.JPanel panel02;
    private javax.swing.JPanel panel03;
    private javax.swing.JPanel panel04;
    private javax.swing.JPanel panel05;
    private javax.swing.JPanel panel06;
    private javax.swing.JPanel panel07;
    private javax.swing.JPanel panel08;
    private javax.swing.JPanel panel09;
    // End of variables declaration//GEN-END:variables
}
